name: GitHub Pages
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build
      run: npm run build:prod
    # - name: Copy Build Artifacts
    #   run: |
    #     # Create a dist/angular-github-actions directory if it doesn't exist
    #     mkdir -p dist/angular-github-actions
    #     # Copy the build artifacts to the dist/project-name directory
    #     pwd
    #     ls -ltr
    #     rsync -av --exclude=dist/ ./ dist/project-name/
    - name: Upload Build Artifacts for the deployment job
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: dist/angular-github-actions

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Current Location
        run: |
         pwd
         ls -ltr
        

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'angular-github-actions-appservice'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_ANGULAR }}
          package: .
